// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU6SbO-Ii5TPdg9BKXwGtVRjF01iuD8J0',
    appId: '1:1008756505572:web:1c43d3bdd524f2f71ee5f1',
    messagingSenderId: '1008756505572',
    projectId: 'app-search-cost',
    authDomain: 'app-search-cost.firebaseapp.com',
    storageBucket: 'app-search-cost.firebasestorage.app',
    measurementId: 'G-Y07XWR1LSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBK5psBnJivk3ffNSnDEjj3KkKTXKsusU',
    appId: '1:1008756505572:android:c194a368326e45f81ee5f1',
    messagingSenderId: '1008756505572',
    projectId: 'app-search-cost',
    storageBucket: 'app-search-cost.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQc_deJVXsnK0ejBVJ4Tu4W2BJpLe5o4U',
    appId: '1:1008756505572:ios:0beac83de3f8e9be1ee5f1',
    messagingSenderId: '1008756505572',
    projectId: 'app-search-cost',
    storageBucket: 'app-search-cost.firebasestorage.app',
    iosBundleId: 'com.example.appSearchCost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQc_deJVXsnK0ejBVJ4Tu4W2BJpLe5o4U',
    appId: '1:1008756505572:ios:0beac83de3f8e9be1ee5f1',
    messagingSenderId: '1008756505572',
    projectId: 'app-search-cost',
    storageBucket: 'app-search-cost.firebasestorage.app',
    iosBundleId: 'com.example.appSearchCost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU6SbO-Ii5TPdg9BKXwGtVRjF01iuD8J0',
    appId: '1:1008756505572:web:ee76b2c49921c0a31ee5f1',
    messagingSenderId: '1008756505572',
    projectId: 'app-search-cost',
    authDomain: 'app-search-cost.firebaseapp.com',
    storageBucket: 'app-search-cost.firebasestorage.app',
    measurementId: 'G-M4YGGSBJL6',
  );
}
